// src/lib/db/index.ts
// Export database utilities
export * from './database';
export * from './utils/mappers';

// Type exports - these will come from Database types generated by Supabase
export type { Database } from './database.types';
