//src/content/certifications.ts
import { Certification } from '@/types/certifications';

export const certifications: Certification[] = [
  {
    id: 'azure-ai-essentials-workloads-ml',
    title: 'Microsoft Azure AI Essentials: Workloads and Machine Learning on Azure',
    issuer: 'LinkedIn Learning',
    issueDate: '2025-11-22',
    description:
      'LinkedIn Learning course on Azure AI workloads, machine learning foundations, and practical AI concepts in Microsoft Azure.',
    skills: ['Machine Learning', 'Azure AI Foundry', 'Artificial Intelligence (AI)'],
    type: 'course',
    filename: 'Microsoft_Azure_AI_Essentials_Workloads_and_Machine_Learning_on_Azure.pdf',
    featured: true,
  },
  {
    id: 'network-defense',
    title: 'Network Defense',
    issuer: 'Cisco Networking Academy',
    issueDate: '2025-05-09',
    description: 'Network Defense certification.',
    skills: ['Network Security', 'Defense'],
    type: 'badge',
    filename: 'NetworkDefenseUpdate20250509-28-afxm48.pdf',
    featured: false,
  },
  {
    id: 'intro-cybersecurity',
    title: 'Introduction to Cybersecurity',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024-11-09',
    description: 'Introduction to Cybersecurity fundamentals.',
    skills: ['Cybersecurity'],
    type: 'badge',
    filename: 'Introduction_to_Cybersecurity_Badge20241109-27-40xb2m.pdf',
    featured: false,
  },
  {
    id: 'univators-cloud',
    title: 'Univators Skilling Future Digital Innovators - Cloud Engineering',
    issuer: 'Univators & Democritus University of Thrace',
    issueDate: '2024-11-08',
    credentialId: '24C014989',
    description: '24-hour course focused on delivering fundamental knowledge in Cloud Engineering.',
    skills: ['Cloud Engineering'],
    type: 'course',
    filename:
      'Certificate-of-Completion-24C014989-Univators-Skilling-Future-Digital-Innovators-CHRISTOS-KERIGKAS.pdf',
    featured: false,
  },
  {
    id: 'oracle-ai',
    title: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate',
    issuer: 'Oracle',
    issueDate: '2024-11-05',
    description: 'Oracle Cloud Infrastructure AI Foundations certification.',
    skills: ['AI', 'Cloud', 'Oracle'],
    type: 'certification',
    filename: 'Oracle_Cloud_Infrastructure_2025_Certified_AI_Foundations_Associate.pdf',
    featured: true,
  },
  {
    id: 'reactjs-beginners',
    title: 'ReactJS for Beginners',
    issuer: 'Great Learning',
    issueDate: '2024-10-03',
    description:
      'Introduction to React.js framework, covering component-based architecture and modern web application development.',
    skills: ['React', 'JavaScript', 'Frontend Development', 'Web Development', 'Component Architecture'],
    type: 'course',
    filename: 'ReactJS_for_Beginners.pdf',
    featured: true,
  },
  {
    id: 'nodejs-beginners',
    title: 'Getting Started with NodeJS',
    issuer: 'Great Learning',
    issueDate: '2024-09-30',
    description:
      'Comprehensive introduction to Node.js development, covering fundamentals of server-side JavaScript programming.',
    skills: ['Node.js', 'JavaScript', 'Backend Development', 'Server-Side Programming'],
    type: 'course',
    filename: 'Getting_Started_with_NodeJS.pdf',
    featured: true,
  },
  {
    id: 'typescript-basics',
    title: 'TypeScript Basics',
    issuer: 'Great Learning',
    issueDate: '2024-09-29',
    description:
      'Fundamentals of TypeScript, covering type systems, interfaces, and modern JavaScript with static typing.',
    skills: ['TypeScript', 'JavaScript', 'Type Safety', 'Static Typing', 'Web Development'],
    type: 'course',
    filename: 'Typescript_Basics.pdf',
    featured: true,
  },
  {
    id: 'negotiation-mastery',
    title: 'Negotiation Mastery',
    issuer: 'Workearly',
    issueDate: '2024-09-23',
    credentialUrl: 'https://www.credly.com/earner/earned/badge/873515c9-f915-4c7d-873b-ce6732d1a118',
    description: 'Professional negotiation skills certification.',
    skills: ['Negotiation', 'Soft Skills', 'Communication'],
    type: 'badge',
    filename: 'Negotiation_Mastery.pdf',
    featured: false,
  },
  {
    id: 'network-addressing',
    title: 'Network Addressing and Basic Troubleshooting',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024-01-13',
    description: 'Network Addressing and Basic Troubleshooting certification.',
    skills: ['Networking', 'Troubleshooting'],
    type: 'badge',
    filename: 'Network_Addressing_and_Basic_Troubleshooting_Badge20240113-34-hs7vyr.pdf',
    featured: false,
  },
  {
    id: 'network-support',
    title: 'Network Support and Security',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024-01-13',
    description: 'Network Support and Security certification.',
    skills: ['Networking', 'Security'],
    type: 'badge',
    filename: 'Network_Support_and_Security_Badge20240113-29-1n54sk.pdf',
    featured: false,
  },
  {
    id: 'networking-basics',
    title: 'Networking Basics',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024-01-13',
    description: 'Networking Basics certification.',
    skills: ['Networking'],
    type: 'badge',
    filename: 'Networking_Basics_Badge20240113-29-5ou4ck.pdf',
    featured: false,
  },
  {
    id: 'networking-devices',
    title: 'Networking Devices and Initial Configuration',
    issuer: 'Cisco Networking Academy',
    issueDate: '2024-01-13',
    description: 'Networking Devices and Initial Configuration certification.',
    skills: ['Networking', 'Configuration'],
    type: 'badge',
    filename: 'Networking_Devices_and_Initial_Configuration_Badge20240113-29-6lb7yw.pdf',
    featured: false,
  },
  {
    id: 'etpe-conference-2023',
    title: '13ο Πανελλήνιο και Διεθνές Συνέδριο «Οι ΤΠΕ στην Εκπαίδευση»',
    issuer: 'ΕΤΠΕ & Διεθνές Πανεπιστήμιο της Ελλάδος',
    issueDate: '2023-09-29',
    description:
      'Παρακολούθηση 13ου Πανελλήνιου και Διεθνούς Συνεδρίου «Οι ΤΠΕ στην Εκπαίδευση» και 11ου Πανελλήνιου Συνεδρίου «Διδακτική της Πληροφορικής», Καβάλα 29/9-1/10/2023.',
    skills: ['Education Technology', 'Computer Science Education'],
    type: 'conference',
    filename: 'Vevaiosi_Parakolouthisis_Kerigkas_Christos.pdf',
    featured: false,
  },
  {
    id: 'quality-management-2023',
    title: 'Εκπαίδευση Προσωπικού και Φοιτητών σε θέματα Διοίκησης Ποιότητας',
    issuer: 'AQS & ABPM - Διεθνές Πανεπιστήμιο της Ελλάδος',
    issueDate: '2023-05-11',
    description:
      'Σεμινάριο Εκπαίδευσης Προσωπικού και Φοιτητών σε θέματα Διοίκησης Ποιότητας με επιτυχή ολοκλήρωση εξετάσεων.',
    skills: ['Quality Management', 'Quality Assurance'],
    type: 'certification',
    filename: 'KERIGKAS_CHRISTOS.pdf',
    featured: false,
  },
  {
    id: 'ltlo-completion',
    title: 'LTLO-15 Certificate of Completion',
    issuer: 'LTLO',
    issueDate: '2022-02-26',
    description: 'LTLO-15 Certificate of Completion.',
    skills: ['Leadership'],
    type: 'certification',
    filename: 'LTLO-15-Certificate-of-Completion.pdf',
    featured: false,
  },
  {
    id: 'ltlo-participation',
    title: 'LTLO-15 Certificate of Participation',
    issuer: 'LTLO',
    issueDate: '2022-02-26',
    description: 'LTLO-15 Certificate of Participation.',
    skills: ['Leadership'],
    type: 'certification',
    filename: 'LTLO-15-Certificate-of-Participation.pdf',
    featured: false,
  },
];
